# Generated by Django 4.2.11 on 2024-04-07 11:50

import authentication.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='defaults/user.png', upload_to='user_profile/', validators=[authentication.validators.profile_picture_validator], verbose_name='profile image'),
        ),
    ]
