version: "3.8"

services:

  database:
    image: postgres:16.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER : admin_user
      POSTGRES_PASSWORD : ThisIsJustAPassword
      PGDATA: /data/postgres
    volumes:
      - ./postgres_data:/data/postgres
  
  backend:
    build: ./backend
    depends_on:
      - database
    ports:
      - 8080:8080
    restart: always
    command: "python manage.py runserver 0.0.0.0:8080"

  frontend:
    build: ./frontend
    ports:
      - 5173:5173
    command: "npm run dev"