version: "3.8"

services:

  database:
    image: postgres:16.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD : ThisIsJustAPassword
      PGDATA: /data/postgres
    volumes:
      - ./postgres_data:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 2s
      retries: 100
    restart: unless-stopped

  backend:
    build: ./backend
    depends_on:
      database:
        condition:
          service_healthy
    ports:
      - 8080:8080
    restart: always
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8080"

  frontend:
    build: ./frontend
    ports:
      - 5173:5173
    command: "npm run dev"