# Generated by Django 4.2.11 on 2024-04-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0015_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='created_at',
            field=models.DateField(auto_created=True, null=True),
        ),
    ]
