# Generated by Django 4.2.11 on 2024-04-15 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_adminlog'),
        ('admin_panel', '0017_alter_order_status'),
    ]

    operations = [
    ]
